### ISSUE TITLE
注入失败

### ISSUE THREAD

**Issue by proc4k** [hxrbunny/wxhelper-docker#2]
![CleanShot 2023-09-17 at 17 58 13@2x](https://github.com/hxrbunny/wxhelper-docker/assets/1990110/369b632e-0774-428d-8e46-1eca918b1cc4)

![CleanShot 2023-09-17 at 18 03 52@2x](https://github.com/hxrbunny/wxhelper-docker/assets/1990110/08f312bf-3756-4eab-b6a8-47ba7bb35b0c)

进入容器内，检查19088 端口没有打开，curl 19088 没有响应

**Comment by proc4k** [comment]
![CleanShot 2023-09-17 at 18 14 36@2x](https://github.com/hxrbunny/wxhelper-docker/assets/1990110/e68715e2-49fd-4c40-924a-3a4d6b8cab98)
19088端口打开了，非POST的请求有响应，但是POST的请求都会hang在那

**Comment by hxrbunny** [comment]
要加上body 。你可以加一个空的，至于为什么，你看一下他的代码就知道了。

**Comment by proc4k** [comment]
感谢 ~
